-- 코드를 
SELECT CHILD.ID
FROM ECOLI_DATA AS GRAND_PARENT
INNER JOIN ECOLI_DATA AS PARENT ON GRAND_PARENT.ID = PARENT.PARENT_ID
INNER JOIN ECOLI_DATA CHILD ON PARENT.ID = CHILD.PARENT_ID
WHERE GRAND_PARENT.PARENT_ID IS NULL
ORDER BY CHILD.ID ASC