-- 코드를 입력하세요
SELECT INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS, ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS INFO
LEFT JOIN REST_REVIEW AS REVIEW ON INFO.REST_ID = REVIEW.REST_ID
WHERE INFO.ADDRESS LIKE '서울%' AND REVIEW.REVIEW_SCORE IS NOT NULL
GROUP BY REST_ID
ORDER BY SCORE DESC, INFO.FAVORITES DESC

