-- 코드를 입력하세요
WITH USER_EARN AS (
SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
WHERE STATUS = 'DONE'
GROUP BY WRITER_ID
)

SELECT G.USER_ID, G.NICKNAME, E.TOTAL_SALES
FROM USED_GOODS_USER AS G
INNER JOIN USER_EARN AS E ON E.WRITER_ID = G.USER_ID
WHERE E.TOTAL_SALES >= 700000
ORDER BY E.TOTAL_SALES ASC